"""
This is generated by modifying read_aruco_markers.py file to read a gridboard of markers in an image
"""

import cv2 as cv
import numpy as np
from cv2 import aruco
import time

def findArucoMarkers(aImage, aDict):
    myImageGrayScaled = cv.cvtColor(aImage, cv.COLOR_BGR2GRAY)
    arucoParameters = aruco.DetectorParameters_create()
    boundaryBoxes, myID, rejectedImages = aruco.detectMarkers(myImageGrayScaled, aDict, parameters=arucoParameters)
    print(myID)
    
    aruco.drawDetectedMarkers(aImage, boundaryBoxes, myID)

def playVideo():
    myVid = cv.VideoCapture(0)

    while 0xFF != ord(' '):
        captureSuccessfull, myFrame = myVid.read()
        
        findArucoMarkers(myFrame, aruco.Dictionary_get(aruco.DICT_4X4_50) )
        cv.imshow("My Video", myFrame)
        cv.waitKey(50)
        
        if cv.waitKey(1) & 0xFF == ord(' '):
            break    
x = cv.imread("C:/Users/NSagi/Music/Desktop/2023_summer_internship/ChArUco_Boards/images/webcam_calibration/testCase.png")
findArucoMarkers(x, aruco.Dictionary_get(aruco.DICT_6X6_1000) )
x = cv.resize(x, (x.shape[1]//2, x.shape[0]//2), interpolation=cv.INTER_CUBIC)
cv.imshow("My x", x)
cv.waitKey(0)
# playVideo()



print("\n\n\nExecution Finished\n\n\n")




